import { useEffect, useState } from "react";
import { Navigate, Link } from "react-router-dom";
import {
  ArrowLeft,
  Loader2,
  Download,
  Check,
  AlertTriangle,
  Link2,
  TrendingUp,
  Coins,
  Building2,
  Sparkles,
} from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { VaultPinGate } from "@/components/founders/VaultPinGate";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { summarizeModel, buildWaveMath } from "@/lib/subscriptionSplitModel";
import zenLogo from "@/assets/zen-logo-horizontal-new.png";

/**
 * Founders · Tschida — private handout page for Michael Tschida.
 *
 * Same gating pattern as every founders page (FounderRoute + PIN), plus a
 * polished branded UI to download the Cheetah/Tschida-ready 50/50 split PDF.
 * The download is generated by the existing `cheetah-export` edge function,
 * which itself enforces founder/admin gating server-side.
 */
export default function FoundersTschida() {
  const { user, isLoading: authLoading } = useAuth();
  const [isFounder, setIsFounder] = useState<boolean | null>(null);

  useEffect(() => {
    if (!user) { setIsFounder(false); return; }
    let cancelled = false;
    (async () => {
      const { data: roles } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", user.id);
      if (cancelled) return;
      const set = new Set((roles ?? []).map((r) => r.role));
      setIsFounder(set.has("founder") || set.has("admin"));
    })();
    return () => { cancelled = true; };
  }, [user]);

  if (authLoading || isFounder === null) {
    return (
      <div className="min-h-[100svh] flex items-center justify-center bg-background">
        <Loader2 className="h-6 w-6 animate-spin text-primary" />
      </div>
    );
  }
  if (!user) return <Navigate to="/auth" replace />;
  if (!isFounder) return <Navigate to="/" replace />;

  return (
    <VaultPinGate userId={user.id}>
      <TschidaContent />
    </VaultPinGate>
  );
}

function fmtUsd(n: number) {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}
function fmtFloor(n: number) {
  return n < 1 ? `$${n.toFixed(3)}` : `$${n.toFixed(2)}`;
}
function fmtUsers(n: number) {
  if (n >= 1_000_000) return `${n / 1_000_000}M`;
  if (n >= 1_000) return `${n / 1_000}K`;
  return `${n}`;
}

function TschidaContent() {
  const rows = buildWaveMath();
  const last = rows[rows.length - 1];
  const [state, setState] = useState<"idle" | "loading" | "ok" | "err">("idle");
  const [shareUrl, setShareUrl] = useState<string | null>(null);

  const handleExport = async () => {
    setState("loading");
    try {
      const clientSummary = summarizeModel();
      const { data, error } = await supabase.functions.invoke("cheetah-export", {
        body: { clientSummary },
      });
      if (error) throw new Error(error.message);
      if (!data?.ok) {
        if (data?.error === "verification_failed") {
          toast({
            title: "Export blocked — verification failed",
            description: data.issues?.[0] ?? "Numbers in this build don't match the canonical model.",
            variant: "destructive",
          });
          setState("err");
          return;
        }
        throw new Error(data?.error ?? "unknown");
      }
      const url: string = data.shareUrl;
      setShareUrl(url);
      try { await navigator.clipboard.writeText(url); } catch { /* */ }
      const a = document.createElement("a");
      a.href = url;
      a.download = "";
      a.target = "_blank";
      a.rel = "noopener";
      document.body.appendChild(a);
      a.click();
      a.remove();
      toast({
        title: "PDF generated · link copied",
        description: "Shareable link copied to clipboard. Download started.",
      });
      setState("ok");
    } catch (e) {
      toast({
        title: "Export failed",
        description: String(e instanceof Error ? e.message : e),
        variant: "destructive",
      });
      setState("err");
    }
  };

  const Icon =
    state === "loading" ? Loader2 :
    state === "ok"      ? Check :
    state === "err"     ? AlertTriangle : Download;

  return (
    <div className="min-h-[100svh] bg-background text-foreground">
      <div
        className="max-w-3xl mx-auto px-4 sm:px-6 pb-16"
        style={{ paddingTop: "calc(env(safe-area-inset-top) + 1.5rem)" }}
      >
        {/* Top bar */}
        <div className="flex items-center justify-between mb-8">
          <Link
            to="/founders"
            className="inline-flex items-center gap-1.5 text-[11px] uppercase tracking-widest text-muted-foreground hover:text-primary"
          >
            <ArrowLeft className="h-3.5 w-3.5" /> Founders Vault
          </Link>
          <span className="text-[10px] uppercase tracking-widest text-amber-400 font-semibold">
            Private · Tschida Only
          </span>
        </div>

        {/* Branded hero */}
        <header className="mb-10 border-b border-border pb-8">
          <img
            src={zenLogo}
            alt="ZenSolar"
            className="h-8 w-auto mb-6 dark:animate-logo-glow"
          />
          <div className="inline-flex items-center gap-2 text-eco text-xs uppercase tracking-widest mb-3">
            <Sparkles className="h-3.5 w-3.5" /> Cofounder Handout · For Michael Tschida
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-3">
            The 50/50 Subscription Split
          </h1>
          <p className="text-base text-muted-foreground leading-relaxed">
            One page. Every dollar Cheetah… every dollar a subscriber pays splits cleanly:
            half buys $ZSOLAR through the liquidity pool, half funds the company. This is
            the math we'll use in every conversation, every pitch, every press question.
          </p>
          <p className="text-xs text-muted-foreground mt-3">
            Internal · For Michael Tschida · Verified against the live transparency model
          </p>
        </header>

        {/* The 50/50 hero */}
        <section className="mb-10 grid grid-cols-2 gap-3">
          <div className="rounded-xl border border-eco/40 bg-eco/[0.06] p-4">
            <div className="inline-flex items-center gap-1.5 text-eco text-[10px] uppercase tracking-widest font-semibold mb-2">
              <Coins className="h-3 w-3" /> 50% → LP (USDC)
            </div>
            <p className="text-3xl font-bold text-eco">$0.50</p>
            <p className="text-[11px] text-muted-foreground mt-2 leading-snug">
              Raises the floor for every $ZSOLAR holder.
            </p>
          </div>
          <div className="rounded-xl border border-border bg-muted/40 p-4">
            <div className="inline-flex items-center gap-1.5 text-foreground/80 text-[10px] uppercase tracking-widest font-semibold mb-2">
              <Building2 className="h-3 w-3" /> 50% → Company (Fiat)
            </div>
            <p className="text-3xl font-bold">$0.50</p>
            <p className="text-[11px] text-muted-foreground mt-2 leading-snug">
              Eng, hardware, legal, gas sponsorship.
            </p>
          </div>
        </section>

        {/* Download CTA */}
        <section className="mb-10 rounded-2xl border border-primary/40 bg-gradient-to-br from-primary/10 via-primary/5 to-transparent p-6 text-center">
          <div className="inline-flex items-center gap-1.5 text-primary text-[10px] uppercase tracking-widest font-semibold mb-3">
            <Download className="h-3 w-3" /> Cheetah-Ready PDF
          </div>
          <h2 className="text-xl font-bold mb-2">Polished one-pager handout</h2>
          <p className="text-sm text-muted-foreground mb-5 max-w-md mx-auto leading-relaxed">
            Server re-computes the model and verifies against the live in-app numbers
            before generating. If anything drifts, the PDF is blocked.
          </p>
          <Button
            onClick={handleExport}
            disabled={state === "loading"}
            size="lg"
            className="gap-2 bg-primary hover:bg-primary/90 min-w-[260px]"
          >
            <Icon className={`h-4 w-4 ${state === "loading" ? "animate-spin" : ""}`} />
            {state === "loading" ? "Verifying & generating…"
              : state === "ok"   ? "Downloaded · Link Copied"
              : state === "err"  ? "Try again"
              : "Download PDF"}
          </Button>
          {shareUrl && (
            <div className="mt-4 inline-flex items-center gap-1.5 text-[11px] text-muted-foreground">
              <Link2 className="h-3 w-3" />
              <a
                href={shareUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-eco hover:underline truncate max-w-[260px] sm:max-w-md"
              >
                {shareUrl}
              </a>
            </div>
          )}
        </section>

        {/* Wave schedule preview */}
        <section className="mb-10">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-4">
            7-Wave Growth Schedule (preview)
          </h2>
          <div className="rounded-xl border border-border overflow-hidden">
            <div className="grid grid-cols-[36px_1fr_64px_72px_72px] sm:grid-cols-[36px_1fr_70px_80px_90px_90px] gap-2 px-3 py-2 bg-muted/60 text-[10px] uppercase tracking-widest font-semibold text-muted-foreground">
              <div>#</div>
              <div>Stage</div>
              <div className="text-right">Subs</div>
              <div className="text-right">ARR</div>
              <div className="text-right hidden sm:block">LP/yr</div>
              <div className="text-right">Floor</div>
            </div>
            {rows.map((r, i) => (
              <div
                key={r.id}
                className={`grid grid-cols-[36px_1fr_64px_72px_72px] sm:grid-cols-[36px_1fr_70px_80px_90px_90px] gap-2 px-3 py-2 text-xs border-t border-border ${
                  i % 2 ? "bg-muted/20" : ""
                }`}
              >
                <div className="text-muted-foreground font-mono">{r.id}</div>
                <div className="font-medium truncate">{r.name}</div>
                <div className="text-right tabular-nums">{fmtUsers(r.users)}</div>
                <div className="text-right tabular-nums">{fmtUsd(r.arr)}</div>
                <div className="text-right tabular-nums text-eco font-semibold hidden sm:block">
                  {fmtUsd(r.lpInjectYr)}
                </div>
                <div className="text-right tabular-nums text-eco font-semibold">
                  {fmtFloor(r.floor)}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* At-scale callouts */}
        <section className="mb-10">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-4">
            At Full Scale · 1M Subscribers
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <ScaleStat label="ARR" value={fmtUsd(last.arr)} />
            <ScaleStat label="LP / yr" value={fmtUsd(last.lpInjectYr)} eco />
            <ScaleStat label="Company / yr" value={fmtUsd(last.companyYr)} />
            <ScaleStat label="Floor" value={fmtFloor(last.floor)} eco />
          </div>
        </section>

        {/* Methodology */}
        <section className="rounded-xl border border-border p-5 mb-8">
          <h2 className="text-base font-semibold mb-3 inline-flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-eco" /> Methodology
          </h2>
          <ul className="space-y-2 text-xs text-muted-foreground leading-relaxed list-disc pl-4">
            <li>Pricing: $9.99 Base + $19.99 Auto-Mint (30% attach) → blended ARPU $12.99/mo.</li>
            <li>Split: 50% USDC into $ZSOLAR LP, 50% to company ops (eng, legal, gas sponsorship).</li>
            <li>LP tranches: $200K USDC + 2M $ZSOLAR seed; one tranche per wave at $0.10 launch price.</li>
            <li>Floor formula: cumulative USDC ÷ cumulative LP-side $ZSOLAR. Conservative — subs only.</li>
            <li>Excludes VPP revenue, token sale, fees. Source: live in-app transparency panel.</li>
          </ul>
        </section>

        <footer className="pt-6 border-t border-border/60 text-center">
          <p className="text-[11px] text-muted-foreground">
            Private link · Do not forward outside the cofounder circle.
          </p>
        </footer>
      </div>
    </div>
  );
}

function ScaleStat({ label, value, eco }: { label: string; value: string; eco?: boolean }) {
  return (
    <div className={`rounded-xl border p-3 ${eco ? "border-eco/40 bg-eco/[0.06]" : "border-border bg-muted/30"}`}>
      <p className={`text-[10px] uppercase tracking-widest font-semibold ${eco ? "text-eco" : "text-muted-foreground"}`}>
        {label}
      </p>
      <p className={`text-xl sm:text-2xl font-bold mt-1 ${eco ? "text-eco" : ""}`}>{value}</p>
    </div>
  );
}
